### ISSUE TITLE
Unable to use library

### ISSUE THREAD

**Issue by DarthKegRaider** [pkourany/DMD_Library#1]
Hi,

Whenever I try to use this library to get my 32x16 LED DMD working on my photon, the webIDE spits out an error:
`build.mk:37:` **\* "No sources found in ".  Stop.
make: **\* [user] Error 2`

The includes I have used are:
`#include "/DMD_Library/DMD.h"
# include "/DMD/SparkIntervalTimer.h"
# include "/DMD_Library/Arial_black_16.h"`

Can you point me in the direction of fixing my photon?  I can get the standard freetronics code to compile on my standard Arduino easily enough.  I am trying to code an NTP enabled clock with my surplus DMD.  Thanks

**Comment by pkourany** [comment]
@DarthKegRaider, I updated the library and published it on the Particle web IDE as "DMD".  When you use the examples, be sure to add the SparkIntervalTimer to your app (also in the web IDE libraries).  Let me know how it goes!

**Comment by DarthKegRaider** [comment]
@pkourany : Thanks!  My code now compiles, hoorah!  I am unable to actually test my clock as yet, since I am away with work and the DMD and photon are in a drawer currently.  I am happy enough for now just tinkering with my code to get the rest working anyway.  Thank you for your speedy fix.

`#include "SparkIntervalTimer/SparkIntervalTimer.h"`
`#include "/DMD/DMD.h"`
`#include "/DMD/Arial_black_16.h"`
