### ISSUE TITLE
Particle.h: No such file or directory

### ISSUE THREAD

**Issue by mmigdal** [pkourany/DMD_Library#2]
Veryfing code using this library in Particle Build fails with this error:

```
DMD/DMD.h:38:22: fatal error: Particle.h: No such file or directory
 #include "Particle.h"
                      ^
```

**Comment by pkourany** [comment]
It seems that when a Core is used as the compile target, "Particle.h is not recognized.  For Photon and Electron targets, it compiles as expected.

**Comment by pkourany** [comment]
Ok, the real issue is that the library will NOT work when compiled against Core firmware v03.4

This library requires Particle firmware v4.5 or later.

No fixes are required.
